### ISSUE TITLE
Allow to provide Git config or disable it

### ISSUE THREAD

**Issue by crqra** [commitizen-tools/commitizen-action#10]
# Description

This action setups Git automatically for the user which is nice in most use-cases but decreases customisation in certain workflows.

For example, one might want to use a custom GitHub App's as the commiter, so he/her can add extra validations around it and more easily audit what workflows are doing what across multiple repositories.

# Possible Solutions

- Allow the user to pass `git_name` and `git_email` inputs or default to GitHub Action's ones
or
- Allow the user to pass a `setup_git` flag to toggle this feature and setup git before running the action

---

If this sounds a reasonable feature for you, I can create a PR adding it.

Thanks in advance!

**Comment by Woile** [comment]
Sounds good! I like it, feel free to create a PR
