### ISSUE TITLE
use $default_branch instead of hardcoding "master"

### ISSUE THREAD

**Issue by docwhat** [commitizen-tools/commitizen-action#14]
The input `branch` should use the actual default branch.  I think you can grab this either by:

1. removing the default key in the `action.yaml` file
2. using $default_branch

**Comment by Woile** [comment]
I have an open PR awaiting reviews 😅 

https://github.com/commitizen-tools/commitizen-action/pull/17

**Comment by Woile** [comment]
Released

**Comment by Woile** [comment]
This already solved now!
