### ISSUE TITLE
Add option pass on NoCommitsFoundError	

### ISSUE THREAD

**Issue by datanrd** [commitizen-tools/commitizen-action#21]
If you use a change type like `ci:`, `build:`, `docs:`, `style:` or `chore:`, it won't bump the version unless you add it to the `bump_pattern` and `bump_map`. You may not want to bump the version for these change types. I propose adding
an option to allow pass on `NoCommitsFoundError`. In the [exit codes documentation](https://commitizen-tools.github.io/commitizen/exit_codes/), it throws an error code of 3 when no commits are found. An option to allow pass on no commits found will allow for simpler workflows. For example, if I update the docs or other change types that don't necessitate a release, with an option like `allow_no_commits` I won't have to put parsing around the commit message to not run. With the this option runs the risks of swallowing unintentional errors.

**Comment by Woile** [comment]
We have planned a feature on commitizen directly that we'll try to implement soon:
https://github.com/commitizen-tools/commitizen/issues/485

**Comment by Kurt-von-Laven** [comment]
This would be great to have. I would guess that this issue makes the Commitizen action incompatible with [Dependabot](https://github.com/dependabot) and similar automated upgrade tools that may routinely open pull requests that only upgrade development dependencies and don't imply a version bump. When I merge a pull request that doesn't imply a version bump, I have to remember to manually delete the subsequent failing Commitizen workflow run, or the build will misleadingly appear to be red after merging a passing pull request.

**Comment by Kurt-von-Laven** [comment]
I saw the aforementioned excellent feature released in Commitizen 2.24.0. Is there a way to pass `--no-raise` through to commitizen from this action, or does a new input need to be added?

**Comment by Woile** [comment]
Please review PR 🙏🏻

**Comment by woile** [comment]
Thanks! I plan to integrate it into the action as soon as I'm back from
holiday (next week).

Regards

**Comment by Kurt-von-Laven** [comment]
@woile, did you mean that reply for a different thread? `--no-raise` has been available via the action since May.
