### ISSUE TITLE
 Generate Github release page

### ISSUE THREAD

**Issue by lyz-code** [commitizen-tools/commitizen-action#3]
## Description

The Github Action currently generates release only with the tag number information but nothing else.

## Possible Solution

The Github Action could generate a detailed Github release page description with the contents of the changelog of that release through the [release api endpoint](https://docs.github.com/en/free-pro-team@latest/rest/reference/repos#create-a-release)

## Additional context

Compare [commitizen releases](https://github.com/commitizen-tools/commitizen/releases) with [python-semantic-release](https://github.com/relekang/python-semantic-release/releases) ones.

Some users use the *Watch releases* to get updated on the evolution of the different software, so it's a nice way to share with your users your progress.

Thanks!

**Comment by christian-hawk** [comment]
@lyz-code, I think you can achieve this by running shell getting the diff from `CHANGELOG.md`.

Something like:
```bash
last_tag=0.0.2;
created_tag=0.0.3;

release_note=$(git diff $last_tag $created_tag> CHANGELOG.md | grep '^+[^++]' | cut -c2-)

git tag $created_tag $created_tag^{} -f -m "$release_note"

```

**Comment by Woile** [comment]
After merging this PR: https://github.com/commitizen-tools/commitizen/pull/359

I'll add the flag to this action, I think should make it easier to create a Release

**Comment by lyz-code** [comment]
Thanks @Woile that makes things much easier

**Comment by Woile** [comment]
https://github.com/commitizen-tools/commitizen-action/blob/master/.github/workflows/bumpversion.yaml

It's working now, I'm closing this issue
