### ISSUE TITLE
Default To Current Branch Rather Than Master

### ISSUE THREAD

**Issue by Kurt-von-Laven** [commitizen-tools/commitizen-action#31]
The README says the default `branch` is the one executing the action, but it's actually [master](https://github.com/commitizen-tools/commitizen-action/blob/bed4ffbccaa55d3326a85784a6df21611005b94b/action.yml#L41). [This](https://github.com/commitizen-tools/commitizen-action/blob/bed4ffbccaa55d3326a85784a6df21611005b94b/entrypoint.sh#L10-L11) is effectively a no-op currently.

**Comment by Woile** [comment]
I think that should be updated, I think this is how it works: https://github.com/commitizen-tools/commitizen-action/blob/master/entrypoint.sh#L10

**Comment by Kurt-von-Laven** [comment]
Yes, that is the line I linked to ^^.
