### ISSUE TITLE
check if commits are compliant

### ISSUE THREAD

**Issue by manang** [commitizen-tools/commitizen-action#42]
Hi,
I don't see a way to check if the commits are compliant with conventional commits.
I need to do this step before the starting of the the jobs inside the action.
Thanks a lot

Angelo

**Comment by Kurt-von-Laven** [comment]
It sounds like you are looking for [`cz check`](https://commitizen-tools.github.io/commitizen/check/)?

**Comment by woile** [comment]
Checking the commits it's out of the scope of this action. My recommendation is to add a step and run `cz check`.

PRs adding support for this will be considered, but we don't have the capacity.
