### ISSUE TITLE
start new workflow when commitizen pushes changelog

### ISSUE THREAD

**Issue by manang** [commitizen-tools/commitizen-action#43]
Hi, do you know how I can start a new workflow when commitizen-actions creates a new changelog and a new tag?
Thanks a lot

**Comment by woile** [comment]
normally you would push the new commit (with the changelog) and the tag to your repo, and then you should have another action "listening" to the new tag and do something about it.

![image](https://user-images.githubusercontent.com/2585816/190382680-686e4ec3-298c-46e6-a32f-065ffc612f33.png)
diagram reference from [a blog post I wrote](https://woile.dev/posts/automating-semver-releases-with-commitizen)

**Comment by manang** [comment]
ok,
thanks
what I'm trying is: in main branch I need to launch a job after a merge. After this I need to launch a job, always on the main branch to do stuff. the second job does not start

**Comment by woile** [comment]
a tag is a reference to a commit, if that commit is in the `main` branch, then you can "run" your action when you detect a new tag. 

For example in commitizen you have this:
https://github.com/commitizen-tools/commitizen/blob/20bcbc4bce1ed4995aa83694706524cf43f50df9/.github/workflows/bumpversion.yml#L1-L22

and then based on the tag you could do something like:
https://github.com/commitizen-tools/commitizen/blob/20bcbc4bce1ed4995aa83694706524cf43f50df9/.github/workflows/pythonpublish.yaml#L1-L6

Option 2, is to make your action, trigger another action. See [this](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_run)

**Comment by manang** [comment]
I'm trying your first option, but in my case the bumb does not trigger the another workflow.
workflow 1:
https://github.com/manang/hicn-sdk/blob/feature/create-tag-if-promote/.github/workflows/master.yml
workflow 2:
https://github.com/manang/hicn-sdk/blob/feature/create-tag-if-promote/.github/workflows/release.yml
I don't understand the mistake.
thanks a lot for your help

**Comment by woile** [comment]
Have you checked our docs? Check this document it might be helpful: https://commitizen-tools.github.io/commitizen/tutorials/github_actions/ (see the warning)

**Comment by manang** [comment]
ok, thanks for your help, solved, the problem was the token.
Angelo
