### ISSUE TITLE
read new tag in following steps

### ISSUE THREAD

**Issue by manang** [commitizen-tools/commitizen-action#48]
is there a way to read the new tag when a changelog+bump are created in a following step?
I tried, but the repo is always the origina, and I don't see the modification.
Thanks a lot
Angelo

**Comment by woile** [comment]
Could you expand? What do you mean by the repo is always the original? Inside the pipeline or you don't see your tag reflected in the repository? Do you get any error?
In the https://github.com/commitizen-tools/commitizen-action#sample-workflow there's an example on how to print the version in a following step

**Comment by manang** [comment]
ok, you solved me with the output. but of course, if you read the last commit, it is not the bump commit, but the previous.

Thanks a lot
