### ISSUE TITLE
this action is installing commitizen == 1.0.0 if the project pinned tomlkit dependency != 0.5.3 

### ISSUE THREAD

**Issue by diefans** [commitizen-tools/commitizen-action#5]
I want to point out, that the assertion/hope that a sane project puts deployment/dev dependencies into its production requirements (`requirements.txt`) cannot be hold: https://github.com/commitizen-tools/commitizen-action/blob/master/entrypoint.sh#L21-L23

IMHO commitizen should install plugins from a specific file, but must not use `requirements.txt`. Project dependencies must not suffer from or be twisted by tool dependencies.

**Comment by Woile** [comment]
Agreed! I didn't think about that.

**Comment by Woile** [comment]
@diefans I've pushed a new change, could you test and check everything is ok?

Thanks!

**Comment by diefans** [comment]
sorry to be late, but seems to work now... tanks
