### ISSUE TITLE
Actor of pushing to branch should be configurable

### ISSUE THREAD

**Issue by lleontop** [commitizen-tools/commitizen-action#55]
Hi,

thanks for this action!
I think there is a problem when the PAT used in the token belongs to one user and the actual commit actor are different which causes errors during pushing of bump commit and tag. 
So if the PAT in the workflow belongs to a bot user A and the actual commit happens from a human user B then if I understand correctly the url in [entrypoint.sh](https://github.com/commitizen-tools/commitizen-action/blob/c17388147d9db38c9eb6690f07b51d18d474162e/entrypoint.sh#L91) will try to authenticate user B with token from A and this will cause a failure in pushing.

I think an input configuring the actual user in this url (defaulting to actor) should suffice. I can also create a PR for this if this solution makes sense!

Thanks!

**Comment by woile** [comment]
A PR would be welcome, thanks!

**Comment by fritz-trawa** [comment]
We need this too so I just created a PR

**Comment by woile** [comment]
thanks 🎉
