### ISSUE TITLE
Container error `fatal: --local can only be used inside a git repository`

### ISSUE THREAD

**Issue by Michele-Alberti** [commitizen-tools/commitizen-action#56]
**Description**
One of my workflows based on _commitizen-action_ is now returning the following error:
![image](https://user-images.githubusercontent.com/62114934/216795688-0b21fc9e-5131-4848-baa0-fc8384d823a7.png)

It used to work properly and the `yaml` configuration file for the workflow was not subjected to changes when the issue occurred.

I have already tested that the error is raised for both `commitizen-action@0.15.1` and `commitizen-action@0.16.0`.

The only step before `commitizen-tools/commitizen-action@0.15.1` is `actions/checkout@v3`.

**References**
A similar issue is reported in [peter-evans/create-pull-request#1170](https://github.com/peter-evans/create-pull-request/issues/1170) and [actions/checkout#760](https://github.com/actions/checkout/issues/760).

**Docker image update**
I've noticed that the image `python:3.8` on _DockerHub_ (used by the `Dockerfile`) was updated just before the first failure of the above-mentioned workflow.
According to the first reference, this issue may be related to _Git_ version: a building process based on different images may explain why the workflow was successful and then failed in two consequent runs, with no configuration changes (and within a few hours of each other).

**Comment by moshevayner** [comment]
Having the exact same issue over here as well, first occurrence of the failure was earlier today (~4 hours ago).
No changed to the CI process were made on our end, which made me check this repo and seems like we weren't the only ones experiencing it.
Thanks for reporting @Michele-Alberti !
Would love to see a quick fix for this, since we heavily rely on this process for our CI/CD process. 🙏🏼 🥺

**Comment by woile** [comment]
My pipelines also broke 😅 ideas on how to fix it are welcome! Gonna take a look at it

**Comment by jmuddle-via** [comment]
As @Michele-Alberti mentioned, the [Python 3.8 image did change on 2023-02-04](https://github.com/docker-library/repo-info/commits/master/repos/python/remote/3.8.md). 

One thought is to fork the repository and pin the image to the previous digest from January.

I think [this diff](https://github.com/docker-library/repo-info/commit/f36b039e437b5fd1c8ac94a41c00f76cbbb46ab5#diff-d1242032f70c016fac180127f749fd152c0db63263babb9ed75bcb5e6ffa9937L4) shows necessary digest. 
I'm assuming that the action runs on Linux AMD64. 

I will try this later today or tomorrow, but if someone else feels inspired, please go ahead.

**Comment by Michele-Alberti** [comment]
My suspect is that it is a consequence of the recent update to _DockerHub's python image_.
Maybe a quick fix is possible with a simple change to the line `FROM python:3.8` inside the `Dockerfile`.

It seems that the image for [3.8.15](https://hub.docker.com/layers/library/python/3.8.15/images/sha256-83614f12599b7666292ef828a916d5b9140dc465f4696163022f1cb269f23621?context=explore) was not changed in the last two months.

Another way could be to downgrade _Git_ to a less recent version inside the `Dockerfile`. I have no idea about the old version though...

**Comment by woile** [comment]
I was thinking of adding to the `entrypoint.sh`:

```
# Fix #56
git config --global --add safe.directory "/__w/commitizen-action/commitizen-action" || true
export GIT_CEILING_DIRECTORIES=/__w # for old git versions
```

Based on [this](https://github.com/actions/checkout/issues/760#issuecomment-1097519290).
Do you think it will work?

**Comment by jmuddle-via** [comment]
@woile that's worth a try, I think the git version in the container is older.

**Comment by woile** [comment]
PR is open #57

**Comment by woile** [comment]
Seems to be working, the tests went ok, and this action was able to release itself.

On a plus, we now use alpine with py3.11, which should make things a bit faster, though I don't know how reliable is alpine this days, I hope better than a couple of years ago.

**Comment by Michele-Alberti** [comment]
I've updated `commitizen-action` to `0.16.1` and now it's working as expected.
Thank you @woile for finding and testing a solution.

I'm closing this issue.
