### ISSUE TITLE
failed to push refs in git-lfs enabled repo

### ISSUE THREAD

**Issue by sanzoghenzo** [commitizen-tools/commitizen-action#7]
Hi, thanks a lot for this action!
I'm trying to use it in my project, that has git-lfs enabled.
When trying to push the new commit, it gives me the following:

```
2021-01-06T18:12:19.0740861Z Pushing to branch...
2021-01-06T18:12:19.7076309Z 
2021-01-06T18:12:19.7078859Z This repository is configured for Git LFS but 'git-lfs' was not found on your path. If you no longer wish to use Git LFS, remove this hook by deleting .git/hooks/pre-push.
2021-01-06T18:12:19.7079533Z 
2021-01-06T18:12:19.7093920Z error: failed to push some refs to '***github.com/sanzoghenzo/wsl-tools.git'
```

I'm not sure if this is a git-lfs problem, of it's only a warning and the problem is unrelated.
bumping manually from my computer (where I have git-lfs) works.

[Here's the workflow used](https://github.com/sanzoghenzo/wsl-tools/blob/main/.github/workflows/autobump.yml), and [here's the last execution with the log](https://github.com/sanzoghenzo/wsl-tools/runs/1658103795?check_suite_focus=true).

Should I enable lfs? If so, how?

Thanks for your help

**Comment by Woile** [comment]
Hello there!
It's my understanding that git lfs must be installed and set up. According to [the docs](https://git-lfs.github.com/)

> Download and install the Git command line extension. Once downloaded and installed, set up Git LFS for your user account by running:
```
git lfs install
```
> You only need to run this once per user account. 

I assume that means per host.

Have you tried adding a step for that?

According to this [stackoverflow anser](https://stackoverflow.com/a/61466160/2047185) you'd have to add:
```
     name: Checkout github repo (+ download lfs dependencies)
        uses: actions/checkout@v2
        with:
          lfs: true
```

Let me know if you manage to solve it.
Regards
