### ISSUE TITLE
Running the action with changelog_increment_filename fails

### ISSUE THREAD

**Issue by brazarb** [commitizen-tools/commitizen-action#71]
Hi all,

excellent action, thank you.

However I'm having an issue when using the argument `changelog_increment_filename`, the action runs successfully if I remove the argument, but obviously no increment change log file is created for the softprops/action-gh-release action.

```toml
[tool.commitizen]
name = "cz_conventional_commits"
tag_format = "v$version"
version_type = "semver"
version_provider = "scm"
update_changelog_on_bump = true
major_version_zero = true
```

```yml
name: Bump Version

on:
  push:
    branches:
      - main

jobs:
  build:
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          token: "${{ secrets.PERSONAL_ACCESS_TOKEN }}"
          fetch-depth: 0
      - name: Create bump and changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          changelog_increment_filename: VERSION.md
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          body_path: "VERSION.md"
          tag_name: ${{ env.REVISION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
```

```log
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv

Notice:  A new release of pip is available: 23.0.1 -> 23.1.2
Notice:  To update, run: pip install --upgrade pip
Commitizen version: 3.5.2
cz --no-raise 21 bump --yes --changelog --check-consistency --changelog-to-stdout >VERSION.md
bump: version 0.0.2 → 0.0.3
tag to create: v0.0.3
increment detected: PATCH

Done!
Repository: org/ClickUpTest
Actor: actor
Pushing to branch...
error: cannot pull with rebase: You have unstaged changes.
error: please commit or stash them.
##[debug]Docker Action run completed with exit code 128
##[debug]REVISION='0.0.3'
##[debug]Set output version = 0.0.3
##[debug]Finishing: Create bump and changelog
```

Replicating this locally with the command above.

`cz --no-raise 21 bump --yes --changelog --check-consistency --changelog-to-stdout >VERSION.md`

Updates the CHANGELOG.md, creates the tag and commits the file. It then it changes the VERSION.md file, but neither it stages it or commits it.

![image](https://github.com/commitizen-tools/commitizen-action/assets/111027880/fd2b1ebc-0bad-4033-94b8-59aa53c730cd)

I tried using another action `EndBug/add-and-commit@v9` to perform the commit, but the commitizen action still throws that error because it looks like it's performing a pull/rebase.

**Comment by woile** [comment]
What is your end goal?
It looks like you are mixing the changelog with the version. With those settings what you are saying is: "update the file where I keep the version with the new changelog". And this creates a conflict, because VERSION is being tracked by git.

Possible solutions:
- if you want the incremented changelog, change the file name to something you are not tracking on git
- if you want to update the version in the file, change the setting on commitizen, see 
https://commitizen-tools.github.io/commitizen/bump/#version_files

**Comment by brazarb** [comment]
Oh that did it... I ignored the VERSION.md from git. I'll stop battling with this now and move onto the next problem.

Thank you
